from PySide6.QtCore import Qt

KEYMAP = {
    "a": Qt.Key.Key_A,
    "b": Qt.Key.Key_B,
    "c": Qt.Key.Key_C,
    "d": Qt.Key.Key_D,
    "e": Qt.Key.Key_E,
    "f": Qt.Key.Key_F,
    "g": Qt.Key.Key_G,
    "h": Qt.Key.Key_H,
    "i": Qt.Key.Key_I,
    "j": Qt.Key.Key_J,
    "k": Qt.Key.Key_K,
    "l": Qt.Key.Key_L,
    "m": Qt.Key.Key_M,
    "n": Qt.Key.Key_N,
    "o": Qt.Key.Key_O,
    "p": Qt.Key.Key_P,
    "q": Qt.Key.Key_Q,
    "r": Qt.Key.Key_R,
    "s": Qt.Key.Key_S,
    "t": Qt.Key.Key_T,
    "u": Qt.Key.Key_U,
    "v": Qt.Key.Key_V,
    "w": Qt.Key.Key_W,
    "x": Qt.Key.Key_X,
    "y": Qt.Key.Key_Y,
    "z": Qt.Key.Key_Z,
    "1": Qt.Key.Key_1,
    "2": Qt.Key.Key_2,
    "3": Qt.Key.Key_3,
    "4": Qt.Key.Key_4,
    "5": Qt.Key.Key_5,
    "6": Qt.Key.Key_6,
    "7": Qt.Key.Key_7,
    "8": Qt.Key.Key_8,
    "9": Qt.Key.Key_9,
    "0": Qt.Key.Key_0,
    ".": Qt.Key.Key_Period,
    "'": Qt.Key.Key_Apostrophe,
}
